# Generated by Django 4.1.3 on 2022-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, to='ads.location'),
        ),
    ]
