# Generated by Django 4.1.3 on 2022-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Администратор', 'admin'), ('Модератор', 'moderator'), ('Участник', 'member')], default='member', max_length=15),
        ),
    ]
