version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: petr
      POSTGRES_PASSWORD: Qwerty_3264
      POSTGRES_DB: project_db
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data:
